package normalize

type currencyNames struct {
	majorSingular string
	majorPlural   string
	minorSingular string
	minorPlural   string
}

var titles = map[string]string{
	"capt.": "Captain",
	"col.":  "Colonel",
	"dr.":   "Doctor",
	"gen.":  "General",
	"gov.":  "Governor",
	"hon.":  "Honorable",
	"jr.":   "Junior",
	"lt.":   "Lieutenant",
	"maj.":  "Major",
	"mr.":   "Mister",
	"mrs.":  "Missus",
	"ms.":   "Mizz",
	"pres.": "President",
	"prof.": "Professor",
	"rep.":  "Representative",
	"rev.":  "Reverend",
	"sen.":  "Senator",
	"sgt.":  "Sergeant",
	"sr.":   "Senior",
	"st.":   "Saint",
}

var spokenAsWord = map[string]struct{}{
	"AIDS":    {},
	"ASAP":    {},
	"CAPTCHA": {},
	"FAQ":     {},
	"FIFA":    {},
	"GIF":     {},
	"IMAX":    {},
	"JPEG":    {},
	"LASER":   {},
	"LOL":     {},
	"NASA":    {},
	"NAFTA":   {},
	"NATO":    {},
	"NIMBY":   {},
	"OPEC":    {},
	"PNG":     {},
	"RADAR":   {},
	"SARS":    {},
	"SCOTUS":  {},
	"SCUBA":   {},
	"UNESCO":  {},
	"UNICEF":  {},
	"Y2K":     {},
}

var symbols = map[string]string{
	"#": "number",
	"&": "and",
	"*": "times",
	"+": "plus",
	"<": "less than",
	"=": "equals",
	">": "greater than",
	"@": "at",
	"~": "tilde",
}

var units = map[string]string{
	"cm":   "centimeters",
	"cm2":  "square centimeters",
	"cl":   "centiliters",
	"db":   "decibels",
	"dl":   "deciliters",
	"gb":   "gigabytes",
	"ghz":  "gigahertz",
	"hr":   "hours",
	"hrs":  "hours",
	"hz":   "hertz",
	"kb":   "kilobytes",
	"kg":   "kilograms",
	"khz":  "kilohertz",
	"km":   "kilometers",
	"km/h": "kilometers per hour",
	"km2":  "square kilometers",
	"kph":  "kilometers per hour",
	"lb":   "pounds",
	"lbs":  "pounds",
	"mb":   "megabytes",
	"mg":   "milligrams",
	"mhz":  "megahertz",
	"min":  "minutes",
	"mins": "minutes",
	"ml":   "milliliters",
	"mm":   "millimeters",
	"mm2":  "square millimeters",
	"mph":  "miles per hour",
	"m/s":  "meters per second",
	"ms":   "milliseconds",
	"nm":   "nanometers",
	"oz":   "ounces",
	"rpm":  "revolutions per minute",
	"sec":  "seconds",
	"secs": "seconds",
	"tb":   "terabytes",
}

var abbreviations = map[string]string{
	"approx.": "approximately",
	"appt.":   "appointment",
	"avg.":    "average",
	"co.":     "company",
	"corp.":   "corporation",
	"dept.":   "department",
	"e.g.":    "for example",
	"est.":    "estimated",
	"etc.":    "et cetera",
	"fig.":    "figure",
	"figs.":   "figures",
	"ft.":     "Fort",
	"i.e.":    "that is",
	"inc.":    "incorporated",
	"max.":    "maximum",
	"min.":    "minimum",
	"misc.":   "miscellaneous",
	"mo.":     "month",
	"mos.":    "months",
	"mt.":     "Mount",
	"no.":     "number",
	"nos.":    "numbers",
	"ref.":    "reference",
	"refs.":   "references",
	"temp.":   "temperature",
	"vol.":    "volume",
	"vs.":     "versus",
	"wk.":     "week",
	"wks.":    "weeks",
	"yr.":     "year",
	"yrs.":    "years",
}

var currencies = map[string]currencyNames{
	"$": {"dollar", "dollars", "cent", "cents"},
	"£": {"pound", "pounds", "penny", "pence"},
	"¥": {"yen", "yen", "sen", "sen"},
	"€": {"euro", "euros", "cent", "cents"},
	"₹": {"rupee", "rupees", "paise", "paise"},
	"₩": {"won", "won", "jeon", "jeon"},
}

var months = []string{
	"",
	"January",
	"February",
	"March",
	"April",
	"May",
	"June",
	"July",
	"August",
	"September",
	"October",
	"November",
	"December",
}
